// src/pages/socialCallback/index.tsx
import { history, useSearchParams } from '@umijs/max';
import { Result, Spin, message } from 'antd';
import { useEffect, useState } from 'react';
import type { LoginParams } from '@/api/types';
import { callback, login } from '@/api/login';
import { useTagsViewStore } from '@/stores/tagsViewStore';
import { getToken, setToken } from '@/utils/auth';
import { appEnv } from '@/utils/env';

export default function SocialCallback() {
  const [params] = useSearchParams();
  const resetTags = useTagsViewStore(state => state.resetTags);
  const [status, setStatus] = useState<'processing' | 'success' | 'error'>('processing');
  const socialCode = params.get('code') || '';
  const socialState = params.get('state') || '';
  const source = params.get('source') || '';

  useEffect(() => {
    const finish = () => {
      window.setTimeout(() => {
        history.replace('/index');
      }, 1200);
    };

    const run = async () => {
      if (!socialCode || !socialState || !source) {
        throw new Error('第三方登录回调参数缺失');
      }

      const data: LoginParams = {
        socialCode,
        socialState,
        source,
        clientId: appEnv.clientId,
        grantType: 'social'
      };

      const res = getToken() ? await callback(data) : await login(data);
      if (res.data?.access_token) {
        setToken(res.data.access_token);
        resetTags();
      }
      message.success(res.msg || '授权成功');
      setStatus('success');
      finish();
    };

    run().catch(error => {
      message.error((error as Error).message || '授权失败');
      setStatus('error');
      finish();
    });
  }, [resetTags, socialCode, socialState, source]);

  if (status === 'processing') {
    return (
      <div className="social-callback-page">
        <Spin size="large" />
      </div>
    );
  }

  return (
    <div className="social-callback-page">
      <Result
        status={status === 'success' ? 'success' : 'error'}
        title={status === 'success' ? '授权成功' : '授权失败'}
      />
    </div>
  );
}

// src/layout/components/SocialCallback/index.vue
<template>
  <div v-loading="loading" class="social-callback"></div>
</template>

<script setup lang="ts">
import { login, callback } from '@/api/login';
import { setToken } from '@/utils/auth';
import Cookies from 'js-cookie';
import { getToken } from '@/utils/auth';
import { LoginData } from '@/api/types';

const route = useRoute();
const loading = ref(true);


/**
 * 接收Route传递的参数
 * @param {Object} route.query.
 */
const code = route.query.code as string;
const state = route.query.state as string;
const source = route.query.source as string;
const tenantId = Cookies.get("tenantId") ? Cookies.get("tenantId") as string : '000000';


const processResponse = async (res: any) => {
  if (res.code !== 200) {
    throw new Error(res.msg);
  }
  if (res.data !== null) {
    setToken(res.data.access_token);
  }
  ElMessage.success(res.msg);
  setTimeout(() => {
    location.href = import.meta.env.VITE_APP_CONTEXT_PATH + 'index';
  }, 2000);
};

const handleError = (error: any) => {
  ElMessage.error(error.message);
  setTimeout(() => {
    location.href = import.meta.env.VITE_APP_CONTEXT_PATH + 'index';
  }, 2000);
};

const callbackByCode = async (data: LoginData) => {
  try {
    const res = await callback(data);
    await processResponse(res);
    loading.value = false;
  } catch (error) {
    handleError(error);
  }
};

const loginByCode = async (data: LoginData) => {
  console.log(2)
  try {
    const res = await login(data);
    await processResponse(res);
    loading.value = false;
  } catch (error) {
    handleError(error);
  }
};

const init = async () => {
  const data: LoginData = {
    socialCode: code,
    socialState: state,
    tenantId: tenantId,
    source: source,
    clientId: 'e5cd7e4891bf95d1d19206ce24a7b32e',
    grantType: 'social'
  };

  if (!getToken()) {
    await loginByCode(data);
  } else {
    await callbackByCode(data);
  }
};

onMounted(() => {
  nextTick(() => {
    init();
  });
});
</script>
