// src/views/system/notice/index.vue
<template>
  <div class="p-2">
    <transition :enter-active-class="proxy?.animate.searchAnimate.enter" :leave-active-class="proxy?.animate.searchAnimate.leave">
      <div v-show="showSearch" class="mb-[10px]">
        <el-card shadow="hover">
          <el-form ref="queryFormRef" :model="queryParams" :inline="true" label-width="68px">
            <el-form-item label="公告标题" prop="noticeTitle">
              <el-input v-model="queryParams.noticeTitle" placeholder="请输入公告标题" clearable style="width: 240px"  style="width: 200px" @keyup.enter="handleQuery" />
            </el-form-item>
            <el-form-item label="操作人员" prop="createByName">
              <el-input v-model="queryParams.createByName" placeholder="请输入操作人员" clearable style="width: 240px"  style="width: 200px" @keyup.enter="handleQuery" />
            </el-form-item>
            <el-form-item label="类型" prop="noticeType">
              <el-select v-model="queryParams.noticeType" placeholder="公告类型" clearable style="width: 240px"  style="width: 200px">
                <el-option v-for="dict in sys_notice_type" :key="dict.value" :label="dict.label" :value="dict.value" />
              </el-select>
            </el-form-item>
            <el-form-item>
              <el-button type="primary" icon="Search" @click="handleQuery">搜索</el-button>
              <el-button icon="Refresh" @click="resetQuery">重置</el-button>
            </el-form-item>
          </el-form>
        </el-card>
      </div>
    </transition>

    <el-card shadow="hover">
      <template #header>
        <el-row :gutter="10" class="mb8">
          <el-col :span="1.5">
            <el-button v-hasPermi="['system:notice:add']" type="primary" plain icon="Plus" @click="handleAdd">新增</el-button>
          </el-col>
          <el-col :span="1.5">
            <el-button v-hasPermi="['system:notice:edit']" type="success" plain icon="Edit" :disabled="single" @click="handleUpdate()"
              >修改</el-button
            >
          </el-col>
          <el-col :span="1.5">
            <el-button v-hasPermi="['system:notice:remove']" type="danger" plain icon="Delete" :disabled="multiple" @click="handleDelete()">
              删除
            </el-button>
          </el-col>
          <right-toolbar v-model:showSearch="showSearch" @query-table="getList"></right-toolbar>
        </el-row>
      </template>

      <el-table v-loading="loading" :data="noticeList" @selection-change="handleSelectionChange">
        <el-table-column type="selection" width="55" align="center" />
        <el-table-column v-if="false" label="序号" align="center" prop="noticeId" width="100" />
        <el-table-column label="公告标题" align="center" prop="noticeTitle" :show-overflow-tooltip="true" />
        <el-table-column label="公告类型" align="center" prop="noticeType" width="100">
          <template #default="scope">
            <dict-tag :options="sys_notice_type" :value="scope.row.noticeType" />
          </template>
        </el-table-column>
        <el-table-column label="状态" align="center" prop="status" width="100">
          <template #default="scope">
            <dict-tag :options="sys_notice_status" :value="scope.row.status" />
          </template>
        </el-table-column>
        <el-table-column label="创建者" align="center" prop="createByName" width="100" />
        <el-table-column label="创建时间" align="center" prop="createTime" width="100">
          <template #default="scope">
            <span>{{ parseTime(scope.row.createTime, '{y}-{m}-{d}') }}</span>
          </template>
        </el-table-column>
        <el-table-column label="操作" align="center" class-name="small-padding fixed-width">
          <template #default="scope">
            <el-tooltip content="修改" placement="top">
              <el-button v-hasPermi="['system:notice:edit']" link type="primary" icon="Edit" @click="handleUpdate(scope.row)"></el-button>
            </el-tooltip>
            <el-tooltip content="删除" placement="top">
              <el-button v-hasPermi="['system:notice:remove']" link type="primary" icon="Delete" @click="handleDelete(scope.row)"></el-button>
            </el-tooltip>
          </template>
        </el-table-column>
      </el-table>

      <pagination v-show="total > 0" v-model:page="queryParams.pageNum" v-model:limit="queryParams.pageSize" :total="total" @pagination="getList" />
    </el-card>
    <!-- 添加或修改公告对话框 -->
    <el-dialog v-model="dialog.visible" :title="dialog.title" width="780px" append-to-body>
      <el-form ref="noticeFormRef" :model="form" :rules="rules" label-width="80px">
        <el-row>
          <el-col :span="12">
            <el-form-item label="公告标题" prop="noticeTitle">
              <el-input v-model="form.noticeTitle" placeholder="请输入公告标题" />
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="公告类型" prop="noticeType">
              <el-select v-model="form.noticeType" placeholder="请选择">
                <el-option v-for="dict in sys_notice_type" :key="dict.value" :label="dict.label" :value="dict.value"></el-option>
              </el-select>
            </el-form-item>
          </el-col>
          <el-col :span="24">
            <el-form-item label="状态">
              <el-radio-group v-model="form.status">
                <el-radio v-for="dict in sys_notice_status" :key="dict.value" :label="dict.value">{{ dict.label }}</el-radio>
              </el-radio-group>
            </el-form-item>
          </el-col>
          <el-col :span="24">
            <el-form-item label="内容">
              <editor v-model="form.noticeContent" :min-height="192" />
            </el-form-item>
          </el-col>
        </el-row>
      </el-form>
      <template #footer>
        <div class="dialog-footer">
          <el-button type="primary" @click="submitForm">确 定</el-button>
          <el-button @click="cancel">取 消</el-button>
        </div>
      </template>
    </el-dialog>
  </div>
</template>

<script setup name="Notice" lang="ts">
import { listNotice, getNotice, delNotice, addNotice, updateNotice } from '@/api/system/notice';
import { NoticeForm, NoticeQuery, NoticeVO } from '@/api/system/notice/types';

const { proxy } = getCurrentInstance() as ComponentInternalInstance;
const { sys_notice_status, sys_notice_type } = toRefs<any>(proxy?.useDict('sys_notice_status', 'sys_notice_type'));

const noticeList = ref<NoticeVO[]>([]);
const loading = ref(true);
const showSearch = ref(true);
const ids = ref<Array<string | number>>([]);
const single = ref(true);
const multiple = ref(true);
const total = ref(0);

const queryFormRef = ref<ElFormInstance>();
const noticeFormRef = ref<ElFormInstance>();

const dialog = reactive<DialogOption>({
  visible: false,
  title: ''
});

const initFormData: NoticeForm = {
  noticeId: undefined,
  noticeTitle: '',
  noticeType: '',
  noticeContent: '',
  status: '0',
  remark: '',
  createByName: ''
};
const data = reactive<PageData<NoticeForm, NoticeQuery>>({
  form: { ...initFormData },
  queryParams: {
    pageNum: 1,
    pageSize: 10,
    noticeTitle: '',
    createByName: '',
    status: '',
    noticeType: ''
  },
  rules: {
    noticeTitle: [{ required: true, message: '公告标题不能为空', trigger: 'blur' }],
    noticeType: [{ required: true, message: '公告类型不能为空', trigger: 'change' }]
  }
});

const { queryParams, form, rules } = toRefs(data);

/** 查询公告列表 */
const getList = async () => {
  loading.value = true;
  const res = await listNotice(queryParams.value);
  noticeList.value = res.rows;
  total.value = res.total;
  loading.value = false;
};
/** 取消按钮 */
const cancel = () => {
  reset();
  dialog.visible = false;
};
/** 表单重置 */
const reset = () => {
  form.value = { ...initFormData };
  noticeFormRef.value?.resetFields();
};
/** 搜索按钮操作 */
const handleQuery = () => {
  queryParams.value.pageNum = 1;
  getList();
};
/** 重置按钮操作 */
const resetQuery = () => {
  queryFormRef.value?.resetFields();
  handleQuery();
};
/** 多选框选中数据 */
const handleSelectionChange = (selection: NoticeVO[]) => {
  ids.value = selection.map((item) => item.noticeId);
  single.value = selection.length != 1;
  multiple.value = !selection.length;
};
/** 新增按钮操作 */
const handleAdd = () => {
  reset();
  dialog.visible = true;
  dialog.title = '添加公告';
};
/**修改按钮操作 */
const handleUpdate = async (row?: NoticeVO) => {
  reset();
  const noticeId = row?.noticeId || ids.value[0];
  const { data } = await getNotice(noticeId);
  Object.assign(form.value, data);
  dialog.visible = true;
  dialog.title = '修改公告';
};
/** 提交按钮 */
const submitForm = () => {
  noticeFormRef.value?.validate(async (valid: boolean) => {
    if (valid) {
      form.value.noticeId ? await updateNotice(form.value) : await addNotice(form.value);
      proxy?.$modal.msgSuccess('操作成功');
      dialog.visible = false;
      await getList();
    }
  });
};
/** 删除按钮操作 */
const handleDelete = async (row?: NoticeVO) => {
  const noticeIds = row?.noticeId || ids.value;
  await proxy?.$modal.confirm('是否确认删除公告编号为"' + noticeIds + '"的数据项？');
  await delNotice(noticeIds);
  await getList();
  proxy?.$modal.msgSuccess('删除成功');
};

onMounted(() => {
  getList();
});
</script>

// src/pages/system/notice/index.tsx
import { DeleteOutlined, EditOutlined, EyeOutlined, PlusOutlined } from '@ant-design/icons';
import {
  ModalForm,
  PageContainer,
  ProFormRadio,
  ProFormSelect,
  ProFormText,
  ProFormTextArea,
  ProTable,
  type ActionType,
  type ProColumns
} from '@ant-design/pro-components';
import { history, useLocation } from '@umijs/max';
import { useBoolean } from 'ahooks';
import { Button, Descriptions, Form, message, Modal, Popconfirm } from 'antd';
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import type { DictData } from '@/api/system/dict/data/types';
import type { NoticeForm, NoticeQuery, NoticeVO } from '@/api/system/notice/types';
import { addNotice, delNotice, getNotice, listNotice, updateNotice } from '@/api/system/notice';
import DictTag from '@/components/common/DictTag';
import EllipsisText from '@/components/common/EllipsisText';
import RichTextEditor from '@/components/common/RichTextEditor';
import RowActions from '@/components/common/RowActions';
import { useDict } from '@/hooks/useDict';
import { useTableSelection } from '@/hooks/useTableSelection';
import { useUserStore } from '@/stores/userStore';
import { resolveOssContent } from '@/utils/ossContent';
import { hasPermi } from '@/utils/permission';
import { toPageQuery, toTableData } from '@/utils/ruoyi';
import { sanitizeHtml } from '@/utils/sanitize';

const defaultNoticeForm: NoticeForm = { status: '0' };
const emptyNoticeContent = '<p>暂无公告内容</p>';

function dictOptions(dicts?: DictData[]) {
  return (dicts || []).map(item => ({ label: item.dictLabel, value: item.dictValue }));
}

function SafeHtmlContent({ html }: { html: string }) {
  const ref = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (ref.current) {
      ref.current.innerHTML = html;
    }
  }, [html]);

  return <div ref={ref} className="notice-detail-content" />;
}

export default function SystemNoticePage() {
  const actionRef = useRef<ActionType | undefined>(undefined);
  const [form] = Form.useForm<NoticeForm>();
  const location = useLocation();
  const userInfo = useUserStore(state => state.userInfo);
  const dicts = useDict('sys_notice_type', 'sys_notice_status');
  const { ids, selectedOne, handleSelectionChange, clearSelection } = useTableSelection<NoticeVO>(row => row.noticeId);
  const [modalOpen, { setTrue: openModal, setFalse: closeModal }] = useBoolean(false);
  const [modalTitle, setModalTitle] = useState('');
  const [detailOpen, { setTrue: openDetailModal, setFalse: closeDetailModal }] = useBoolean(false);
  const [detail, setDetail] = useState<NoticeVO>();

  const canAdd = hasPermi(userInfo, ['system:notice:add']);
  const canEdit = hasPermi(userInfo, ['system:notice:edit']);
  const canRemove = hasPermi(userInfo, ['system:notice:remove']);
  const noticeTypeOptions = useMemo(() => dictOptions(dicts.sys_notice_type), [dicts.sys_notice_type]);
  const noticeStatusOptions = useMemo(() => dictOptions(dicts.sys_notice_status), [dicts.sys_notice_status]);

  const openAdd = () => {
    form.resetFields();
    form.setFieldsValue(defaultNoticeForm);
    setModalTitle('添加公告');
    openModal();
  };

  const openEdit = async (row?: NoticeVO) => {
    const target = row || selectedOne;
    if (!target?.noticeId) return;
    const res = await getNotice(target.noticeId);
    form.resetFields();
    form.setFieldsValue(res.data);
    setModalTitle('修改公告');
    openModal();
  };

  const openDetail = useCallback(
    async (row: NoticeVO | string | number) => {
      const noticeId = typeof row === 'object' ? row.noticeId : row;
      const res = await getNotice(noticeId);
      const noticeContent = await resolveOssContent(res.data.noticeContent);
      setDetail({ ...res.data, noticeContent });
      openDetailModal();
    },
    [openDetailModal]
  );

  const closeDetail = () => {
    closeDetailModal();
    setDetail(undefined);
    const params = new URLSearchParams(location.search);
    if (!params.has('noticeId')) {
      return;
    }
    params.delete('noticeId');
    const search = params.toString();
    history.replace(`${location.pathname}${search ? `?${search}` : ''}`);
  };

  const submitForm = async (values: NoticeForm) => {
    values.noticeId ? await updateNotice(values) : await addNotice(values);
    message.success('操作成功');
    form.resetFields();
    actionRef.current?.reload();
    return true;
  };

  const remove = async (row?: NoticeVO) => {
    await delNotice(row?.noticeId || ids);
    message.success('删除成功');
    clearSelection();
    actionRef.current?.reloadAndRest?.();
  };

  useEffect(() => {
    const noticeId = new URLSearchParams(location.search).get('noticeId');
    if (noticeId) {
      openDetail(noticeId);
    }
  }, [location.search, openDetail]);

  const safeNoticeContent = useMemo(
    () => sanitizeHtml(detail?.noticeContent || emptyNoticeContent),
    [detail?.noticeContent]
  );

  const columns: ProColumns<NoticeVO>[] = [
    {
      title: '公告标题',
      dataIndex: 'noticeTitle',
      width: 220,
      render: (_, row) => <EllipsisText value={row.noticeTitle} maxWidth={200} />
    },
    { title: '操作人员', dataIndex: 'createByName', width: 130 },
    {
      title: '公告类型',
      dataIndex: 'noticeType',
      valueType: 'select',
      width: 120,
      fieldProps: { options: noticeTypeOptions },
      render: (_, row) => <DictTag options={dicts.sys_notice_type} value={row.noticeType} />
    },
    {
      title: '状态',
      dataIndex: 'status',
      search: false,
      width: 100,
      render: (_, row) => <DictTag options={dicts.sys_notice_status} value={row.status} />
    },
    { title: '创建时间', dataIndex: 'createTime', valueType: 'dateTime', search: false, width: 170 },
    {
      title: '操作',
      valueType: 'option',
      width: 130,
      fixed: 'right',
      render: (_, row) => (
        <RowActions
          actions={[
            { key: 'detail', label: '详情', icon: <EyeOutlined />, onClick: () => openDetail(row) },
            canEdit && { key: 'edit', label: '修改', icon: <EditOutlined />, onClick: () => openEdit(row) },
            canRemove && {
              key: 'delete',
              label: '删除',
              icon: <DeleteOutlined />,
              danger: true,
              confirm: `是否确认删除公告编号为"${row.noticeId}"的数据项？`,
              onClick: () => remove(row)
            }
          ]}
        />
      )
    }
  ];

  return (
    <PageContainer title="公告管理">
      <ProTable<NoticeVO, NoticeQuery>
        actionRef={actionRef}
        rowKey="noticeId"
        columns={columns}
        scroll={{ x: 1120 }}
        search={{ labelWidth: 90 }}
        rowSelection={{ selectedRowKeys: ids, onChange: handleSelectionChange }}
        request={async params => {
          const res = await listNotice(toPageQuery(params));
          return toTableData(res);
        }}
        toolbar={{ title: '公告列表' }}
        toolBarRender={() => [
          canAdd && (
            <Button key="add" type="primary" icon={<PlusOutlined />} onClick={openAdd}>
              新增
            </Button>
          ),
          canEdit && (
            <Button key="edit" disabled={!selectedOne} icon={<EditOutlined />} onClick={() => openEdit()}>
              修改
            </Button>
          ),
          canRemove && (
            <Popconfirm key="delete" title={`是否确认删除公告编号为"${ids}"的数据项？`} onConfirm={() => remove()}>
              <Button danger disabled={!ids.length} icon={<DeleteOutlined />}>
                删除
              </Button>
            </Popconfirm>
          )
        ]}
      />

      <ModalForm<NoticeForm>
        title={modalTitle}
        open={modalOpen}
        width={780}
        form={form}
        layout="vertical"
        initialValues={defaultNoticeForm}
        modalProps={{ destroyOnHidden: true, onCancel: closeModal }}
        onOpenChange={open => !open && closeModal()}
        onFinish={submitForm}
      >
        <ProFormText name="noticeId" hidden />
        <div className="form-grid">
          <ProFormText name="noticeTitle" label="公告标题" rules={[{ required: true, message: '公告标题不能为空' }]} />
          <ProFormSelect
            name="noticeType"
            label="公告类型"
            rules={[{ required: true, message: '公告类型不能为空' }]}
            options={noticeTypeOptions}
            placeholder="请选择"
          />
        </div>
        <ProFormRadio.Group name="status" label="状态" options={noticeStatusOptions} />
        <Form.Item name="noticeContent" label="内容">
          <RichTextEditor minHeight={192} />
        </Form.Item>
        <ProFormTextArea name="remark" label="备注" fieldProps={{ rows: 3 }} />
      </ModalForm>

      <Modal title="公告详情" open={detailOpen} width={820} footer={null} onCancel={closeDetail}>
        <div className="notice-detail">
          <h2>{detail?.noticeTitle || '-'}</h2>
          <Descriptions column={2} size="small">
            <Descriptions.Item label="类型">
              <DictTag options={dicts.sys_notice_type} value={detail?.noticeType} />
            </Descriptions.Item>
            <Descriptions.Item label="状态">
              <DictTag options={dicts.sys_notice_status} value={detail?.status} />
            </Descriptions.Item>
            <Descriptions.Item label="创建者">{detail?.createByName || '-'}</Descriptions.Item>
            <Descriptions.Item label="创建时间">{detail?.createTime || '-'}</Descriptions.Item>
          </Descriptions>
          <SafeHtmlContent html={safeNoticeContent} />
        </div>
      </Modal>
    </PageContainer>
  );
}
