// src/pages/tool/gen/index.tsx
import {
  CopyOutlined,
  DeleteOutlined,
  DownloadOutlined,
  EditOutlined,
  EyeOutlined,
  SyncOutlined,
  UploadOutlined
} from '@ant-design/icons';
import { PageContainer, ProTable, type ActionType, type ProColumns } from '@ant-design/pro-components';
import { history, useLocation } from '@umijs/max';
import { useBoolean } from 'ahooks';
import { Button, message, Modal, Popconfirm, Space, Tabs, Tooltip } from 'antd';
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { Prism as SyntaxHighlighter } from 'react-syntax-highlighter';
import { oneDark } from 'react-syntax-highlighter/dist/esm/styles/prism';
import type { TableQuery, TableVO } from '@/api/tool/gen/types';
import { batchGenCode, delTable, getDataNames, listTable, previewTable, synchDb } from '@/api/tool/gen';
import EllipsisText from '@/components/common/EllipsisText';
import { useUserStore } from '@/stores/userStore';
import { saveValidatedBlob } from '@/utils/download';
import { hasPermi } from '@/utils/permission';
import { addDateRange, toPageQuery, toTableData } from '@/utils/ruoyi';
import ImportTableModal from './components/ImportTableModal';

function previewName(path: string) {
  const fileName = path.substring(path.lastIndexOf('/') + 1);
  return fileName.includes('.vm') ? fileName.substring(0, fileName.indexOf('.vm')) : fileName;
}

function previewLanguage(name: string) {
  const ext = name.toLowerCase().split('.').pop();
  const languageMap: Record<string, string> = {
    java: 'java',
    xml: 'xml',
    ts: 'typescript',
    tsx: 'tsx',
    vue: 'vue',
    sql: 'sql',
    json: 'json',
    yml: 'yaml',
    yaml: 'yaml',
    js: 'javascript',
    jsx: 'jsx',
    html: 'html',
    css: 'css',
    less: 'less'
  };
  return (ext && languageMap[ext]) || 'text';
}

export default function ToolGenPage() {
  const location = useLocation();
  const actionRef = useRef<ActionType | undefined>(undefined);
  const userInfo = useUserStore(state => state.userInfo);
  const [selectedRows, setSelectedRows] = useState<TableVO[]>([]);
  const [dataNames, setDataNames] = useState<string[]>([]);
  const [previewOpen, { setTrue: openPreviewModal, setFalse: closePreviewModal }] = useBoolean(false);
  const [previewData, setPreviewData] = useState<Record<string, string>>({});
  const [previewActive, setPreviewActive] = useState('');
  const [importOpen, { setTrue: openImportModal, setFalse: closeImportModal }] = useBoolean(false);
  const [currentDataName, setCurrentDataName] = useState<string>();
  const [currentPage, setCurrentPage] = useState(
    () => Number(new URLSearchParams(location.search).get('pageNum')) || 1
  );

  const canCode = hasPermi(userInfo, ['tool:gen:code']);
  const canImport = hasPermi(userInfo, ['tool:gen:import']);
  const canEdit = hasPermi(userInfo, ['tool:gen:edit']);
  const canRemove = hasPermi(userInfo, ['tool:gen:remove']);
  const canPreview = hasPermi(userInfo, ['tool:gen:preview']);
  const selectedIds = selectedRows.map(item => item.tableId).filter(Boolean);
  const selectedOne = selectedRows.length === 1 ? selectedRows[0] : undefined;
  const previewItems = useMemo(() => Object.entries(previewData), [previewData]);

  const loadDataNames = useCallback(async () => {
    const res = await getDataNames();
    const names = res.data || [];
    setDataNames(names);
    return names;
  }, []);

  const openEditTable = (tableId?: string | number) => {
    if (!tableId) return;
    history.push(`/tool/gen-edit/index/${tableId}?pageNum=${currentPage}`);
  };

  useEffect(() => {
    loadDataNames();
  }, [loadDataNames]);

  const handleGenTable = async (row?: TableVO) => {
    const rows = row ? [row] : selectedRows;
    if (!rows.length) {
      message.error('请选择要生成的数据');
      return;
    }
    const tableIdStr = rows.map(item => item.tableId).join(',');
    const blob = await batchGenCode(tableIdStr);
    await saveValidatedBlob(blob, 'ruoyi.zip');
  };

  const handlePreview = async (row: TableVO) => {
    const res = await previewTable(row.tableId);
    const data = res.data || {};
    setPreviewData(data);
    setPreviewActive(Object.keys(data)[0] ? previewName(Object.keys(data)[0]) : '');
    openPreviewModal();
  };

  const copyPreview = async (value: string) => {
    await navigator.clipboard.writeText(value);
    message.success('复制成功');
  };

  const handleSynchDb = async (row: TableVO) => {
    await synchDb(row.tableId);
    message.success('同步成功');
    actionRef.current?.reload();
  };

  const handleDelete = async (row?: TableVO) => {
    const ids = row?.tableId || selectedIds;
    if (!ids || (Array.isArray(ids) && ids.length === 0)) return;
    await delTable(ids);
    message.success('删除成功');
    setSelectedRows([]);
    actionRef.current?.reloadAndRest?.();
  };

  const openImportTable = async () => {
    await loadDataNames();
    openImportModal();
  };

  const columns: ProColumns<TableVO>[] = [
    {
      title: '数据源',
      dataIndex: 'dataName',
      valueType: 'select',
      fieldProps: {
        allowClear: true,
        showSearch: true,
        options: [{ label: '全部', value: '' }, ...dataNames.map(item => ({ label: item, value: item }))]
      },
      width: 150,
      render: (_, row) => <EllipsisText value={row.dataName} maxWidth={130} />
    },
    {
      title: '表名称',
      dataIndex: 'tableName',
      width: 180,
      render: (_, row) => <EllipsisText value={row.tableName} maxWidth={160} />
    },
    {
      title: '表描述',
      dataIndex: 'tableComment',
      width: 180,
      render: (_, row) => <EllipsisText value={row.tableComment} maxWidth={160} />
    },
    {
      title: '实体',
      dataIndex: 'className',
      search: false,
      width: 180,
      render: (_, row) => <EllipsisText value={row.className} maxWidth={160} />
    },
    {
      title: '创建时间',
      dataIndex: 'createTime',
      valueType: 'dateTime',
      search: false,
      width: 170
    },
    {
      title: '创建时间',
      dataIndex: 'dateRange',
      valueType: 'dateRange',
      hideInTable: true,
      search: { transform: value => ({ dateRange: value }) }
    },
    { title: '更新时间', dataIndex: 'updateTime', valueType: 'dateTime', search: false, width: 170 },
    {
      title: '操作',
      valueType: 'option',
      width: 230,
      fixed: 'right',
      render: (_, row) => (
        <Space size={4}>
          {canPreview && (
            <Tooltip title="预览">
              <Button type="link" size="small" icon={<EyeOutlined />} onClick={() => handlePreview(row)} />
            </Tooltip>
          )}
          {canEdit && (
            <Tooltip title="编辑">
              <Button type="link" size="small" icon={<EditOutlined />} onClick={() => openEditTable(row.tableId)} />
            </Tooltip>
          )}
          {canRemove && (
            <Popconfirm title={`是否确认删除表编号为"${row.tableId}"的数据项？`} onConfirm={() => handleDelete(row)}>
              <Tooltip title="删除">
                <Button type="link" danger size="small" icon={<DeleteOutlined />} />
              </Tooltip>
            </Popconfirm>
          )}
          {canEdit && (
            <Popconfirm title={`确认要强制同步"${row.tableName}"表结构吗？`} onConfirm={() => handleSynchDb(row)}>
              <Tooltip title="同步">
                <Button type="link" size="small" icon={<SyncOutlined />} />
              </Tooltip>
            </Popconfirm>
          )}
          {canCode && (
            <Tooltip title="生成代码">
              <Button type="link" size="small" icon={<DownloadOutlined />} onClick={() => handleGenTable(row)} />
            </Tooltip>
          )}
        </Space>
      )
    }
  ];

  return (
    <PageContainer title="代码生成">
      <ProTable<TableVO, TableQuery & { dateRange?: [string, string] }>
        actionRef={actionRef}
        rowKey="tableId"
        columns={columns}
        scroll={{ x: 1300 }}
        search={{ labelWidth: 90 }}
        pagination={{ defaultCurrent: currentPage, defaultPageSize: 10, showSizeChanger: true }}
        rowSelection={{
          selectedRowKeys: selectedIds,
          onChange: (_, rows) => setSelectedRows(rows)
        }}
        request={async params => {
          const { dateRange, ...tableParams } = params;
          setCurrentPage(tableParams.current || 1);
          setCurrentDataName(tableParams.dataName || undefined);
          const query = addDateRange(toPageQuery(tableParams), dateRange);
          const res = await listTable(query);
          return toTableData(res);
        }}
        toolbar={{ title: '数据表列表' }}
        toolBarRender={() => [
          canCode && (
            <Button key="gen" type="primary" icon={<DownloadOutlined />} onClick={() => handleGenTable()}>
              生成
            </Button>
          ),
          canImport && (
            <Button key="import" icon={<UploadOutlined />} onClick={openImportTable}>
              导入
            </Button>
          ),
          canEdit && (
            <Button
              key="edit"
              icon={<EditOutlined />}
              disabled={!selectedOne}
              onClick={() => openEditTable(selectedOne?.tableId)}
            >
              修改
            </Button>
          ),
          canRemove && (
            <Popconfirm key="delete" title="是否确认删除选中的代码生成表？" onConfirm={() => handleDelete()}>
              <Button danger icon={<DeleteOutlined />} disabled={!selectedIds.length}>
                删除
              </Button>
            </Popconfirm>
          )
        ]}
      />

      <Modal title="代码预览" open={previewOpen} width="80%" onCancel={closePreviewModal} footer={null} destroyOnHidden>
        <Tabs
          activeKey={previewActive}
          onChange={setPreviewActive}
          items={previewItems.map(([key, value]) => ({
            key: previewName(key),
            label: previewName(key),
            children: (
              <div>
                <Button
                  type="link"
                  icon={<CopyOutlined />}
                  onClick={() => copyPreview(value)}
                  style={{ float: 'right' }}
                >
                  复制
                </Button>
                <SyntaxHighlighter
                  language={previewLanguage(previewName(key))}
                  style={oneDark}
                  showLineNumbers
                  wrapLongLines
                  customStyle={{ maxHeight: '60vh', clear: 'both', margin: 0, borderRadius: 6 }}
                >
                  {value}
                </SyntaxHighlighter>
              </div>
            )
          }))}
        />
      </Modal>

      <ImportTableModal
        open={importOpen}
        dataNames={dataNames}
        initialDataName={currentDataName}
        onCancel={closeImportModal}
        onSuccess={() => {
          closeImportModal();
          actionRef.current?.reloadAndRest?.();
        }}
      />
    </PageContainer>
  );
}

// src/views/tool/gen/index.vue
<template>
  <div class="p-2">
    <transition :enter-active-class="proxy?.animate.searchAnimate.enter" :leave-active-class="proxy?.animate.searchAnimate.leave">
      <div v-show="showSearch" class="mb-[10px]">
        <el-card shadow="hover">
          <el-form ref="queryFormRef" :model="queryParams" :inline="true" label-width="68px">
            <el-form-item label="数据源" prop="dataName">
              <el-select v-model="queryParams.dataName" filterable clearable placeholder="请选择/输入数据源名称" style="width: 200px">
                <el-option key="" label="全部" value="" />
                <el-option v-for="item in dataNameList" :key="item" :label="item" :value="item"> </el-option>
              </el-select>
            </el-form-item>
            <el-form-item label="表名称" prop="tableName">
              <el-input v-model="queryParams.tableName" placeholder="请输入表名称" clearable style="width: 240px" @keyup.enter="handleQuery" />
            </el-form-item>
            <el-form-item label="表描述" prop="tableComment">
              <el-input v-model="queryParams.tableComment" placeholder="请输入表描述" clearable style="width: 240px" @keyup.enter="handleQuery" />
            </el-form-item>
            <el-form-item label="创建时间" style="width: 308px">
              <el-date-picker
                v-model="dateRange"
                value-format="YYYY-MM-DD"
                type="daterange"
                range-separator="-"
                start-placeholder="开始日期"
                end-placeholder="结束日期"
              ></el-date-picker>
            </el-form-item>
            <el-form-item>
              <el-button type="primary" icon="Search" @click="handleQuery">搜索</el-button>
              <el-button icon="Refresh" @click="resetQuery">重置</el-button>
            </el-form-item>
          </el-form>
        </el-card>
      </div>
    </transition>

    <el-card shadow="hover">
      <template #header>
        <el-row :gutter="10" class="mb8">
          <el-col :span="1.5">
            <el-button v-hasPermi="['tool:gen:code']" type="primary" plain icon="Download" @click="handleGenTable()">生成</el-button>
          </el-col>
          <el-col :span="1.5">
            <el-button v-hasPermi="['tool:gen:import']" type="info" plain icon="Upload" @click="openImportTable">导入</el-button>
          </el-col>
          <el-col :span="1.5">
            <el-button v-hasPermi="['tool:gen:edit']" type="success" plain icon="Edit" :disabled="single" @click="handleEditTable()">修改</el-button>
          </el-col>
          <el-col :span="1.5">
            <el-button v-hasPermi="['tool:gen:remove']" type="danger" plain icon="Delete" :disabled="multiple" @click="handleDelete()">
              删除
            </el-button>
          </el-col>
          <right-toolbar v-model:showSearch="showSearch" @query-table="getList"></right-toolbar>
        </el-row>
      </template>

      <el-table v-loading="loading" :data="tableList" @selection-change="handleSelectionChange">
        <el-table-column type="selection" align="center" width="55"></el-table-column>
        <el-table-column label="序号" type="index" width="50" align="center">
          <template #default="scope">
            <span>{{ (queryParams.pageNum - 1) * queryParams.pageSize + scope.$index + 1 }}</span>
          </template>
        </el-table-column>
        <el-table-column label="数据源" align="center" prop="dataName" :show-overflow-tooltip="true" />
        <el-table-column label="表名称" align="center" prop="tableName" :show-overflow-tooltip="true" />
        <el-table-column label="表描述" align="center" prop="tableComment" :show-overflow-tooltip="true" />
        <el-table-column label="实体" align="center" prop="className" :show-overflow-tooltip="true" />
        <el-table-column label="创建时间" align="center" prop="createTime" width="160" />
        <el-table-column label="更新时间" align="center" prop="updateTime" width="160" />
        <el-table-column label="操作" align="center" width="330" class-name="small-padding fixed-width">
          <template #default="scope">
            <el-tooltip content="预览" placement="top">
              <el-button v-hasPermi="['tool:gen:preview']" link type="primary" icon="View" @click="handlePreview(scope.row)"></el-button>
            </el-tooltip>
            <el-tooltip content="编辑" placement="top">
              <el-button v-hasPermi="['tool:gen:edit']" link type="primary" icon="Edit" @click="handleEditTable(scope.row)"></el-button>
            </el-tooltip>
            <el-tooltip content="删除" placement="top">
              <el-button v-hasPermi="['tool:gen:remove']" link type="primary" icon="Delete" @click="handleDelete(scope.row)"></el-button>
            </el-tooltip>
            <el-tooltip content="同步" placement="top">
              <el-button v-hasPermi="['tool:gen:edit']" link type="primary" icon="Refresh" @click="handleSynchDb(scope.row)"></el-button>
            </el-tooltip>
            <el-tooltip content="生成代码" placement="top">
              <el-button v-hasPermi="['tool:gen:code']" link type="primary" icon="Download" @click="handleGenTable(scope.row)"></el-button>
            </el-tooltip>
          </template>
        </el-table-column>
      </el-table>
      <pagination v-show="total > 0" v-model:page="queryParams.pageNum" v-model:limit="queryParams.pageSize" :total="total" @pagination="getList" />
    </el-card>

    <!-- 预览界面 -->
    <el-dialog v-model="dialog.visible" :title="dialog.title" width="80%" top="5vh" append-to-body class="scrollbar">
      <el-tabs v-model="preview.activeName">
        <el-tab-pane
          v-for="(value, key) in preview.data"
          :key="value"
          :label="key.substring(key.lastIndexOf('/') + 1, key.indexOf('.vm'))"
          :name="key.substring(key.lastIndexOf('/') + 1, key.indexOf('.vm'))"
        >
          <el-link v-copyText="value" v-copyText:callback="copyTextSuccess" :underline="false" icon="DocumentCopy" style="float: right">
            &nbsp;复制
          </el-link>
          <pre>{{ value }}</pre>
        </el-tab-pane>
      </el-tabs>
    </el-dialog>
    <import-table ref="importRef" @ok="handleQuery" />
  </div>
</template>

<script setup name="Gen" lang="ts">
import { listTable, previewTable, delTable, genCode, synchDb, getDataNames } from '@/api/tool/gen';
import { TableQuery, TableVO } from '@/api/tool/gen/types';
import router from '@/router';
import ImportTable from './importTable.vue';

const route = useRoute();
const { proxy } = getCurrentInstance() as ComponentInternalInstance;

const tableList = ref<TableVO[]>([]);
const loading = ref(true);
const showSearch = ref(true);
const ids = ref<Array<string | number>>([]);
const single = ref(true);
const multiple = ref(true);
const total = ref(0);
const dateRange = ref<[DateModelType, DateModelType]>(['', '']);
const uniqueId = ref('');
const dataNameList = ref<Array<string>>([]);

const queryFormRef = ref<ElFormInstance>();
const importRef = ref<InstanceType<typeof ImportTable>>();

const queryParams = ref<TableQuery>({
  pageNum: 1,
  pageSize: 10,
  tableName: '',
  tableComment: '',
  dataName: ''
});

const preview = ref<{
  data: Record<string, string>;
  activeName: string;
}>({
  data: {},
  activeName: 'domain.java'
});
const dialog = reactive<DialogOption>({
  visible: false,
  title: '代码预览'
});

onActivated(() => {
  const time = route.query.t;
  if (time != null && time != uniqueId.value) {
    uniqueId.value = time as string;
    queryParams.value.pageNum = Number(route.query.pageNum);
    dateRange.value = ['', ''];
    queryFormRef.value?.resetFields();
    getList();
  }
});

/** 查询多数据源名称 */
const getDataNameList = async () => {
  const res = await getDataNames();
  dataNameList.value = res.data;
};

/** 查询表集合 */
const getList = async () => {
  loading.value = true;
  const res = await listTable(proxy?.addDateRange(queryParams.value, dateRange.value));
  tableList.value = res.rows;
  total.value = res.total;
  loading.value = false;
};
/** 搜索按钮操作 */
const handleQuery = () => {
  queryParams.value.pageNum = 1;
  getList();
};
/** 生成代码操作 */
const handleGenTable = async (row?: TableVO) => {
  const tbIds = row?.tableId || ids.value;
  if (tbIds == '') {
    proxy?.$modal.msgError('请选择要生成的数据');
    return;
  }
  if (row?.genType === '1') {
    await genCode(row.tableId);
    proxy?.$modal.msgSuccess('成功生成到自定义路径：' + row.genPath);
  } else {
    proxy?.$download.zip('/tool/gen/batchGenCode?tableIdStr=' + tbIds, 'ruoyi.zip');
  }
};
/** 同步数据库操作 */
const handleSynchDb = async (row: TableVO) => {
  const tableId = row.tableId;
  await proxy?.$modal.confirm('确认要强制同步"' + row.tableName + '"表结构吗？');
  await synchDb(tableId);
  proxy?.$modal.msgSuccess('同步成功');
};
/** 打开导入表弹窗 */
const openImportTable = () => {
  importRef.value?.show(queryParams.value.dataName);
};
/** 重置按钮操作 */
const resetQuery = () => {
  dateRange.value = ['', ''];
  queryFormRef.value?.resetFields();
  handleQuery();
};
/** 预览按钮 */
const handlePreview = async (row: TableVO) => {
  const res = await previewTable(row.tableId);
  preview.value.data = res.data;
  dialog.visible = true;
  preview.value.activeName = 'domain.java';
};
/** 复制代码成功 */
const copyTextSuccess = () => {
  proxy?.$modal.msgSuccess('复制成功');
};
// 多选框选中数据
const handleSelectionChange = (selection: TableVO[]) => {
  ids.value = selection.map((item) => item.tableId);
  single.value = selection.length != 1;
  multiple.value = !selection.length;
};
/** 修改按钮操作 */
const handleEditTable = (row?: TableVO) => {
  const tableId = row?.tableId || ids.value[0];
  router.push({ path: '/tool/gen-edit/index/' + tableId, query: { pageNum: queryParams.value.pageNum } });
};
/** 删除按钮操作 */
const handleDelete = async (row?: TableVO) => {
  const tableIds = row?.tableId || ids.value;
  await proxy?.$modal.confirm('是否确认删除表编号为"' + tableIds + '"的数据项？');
  await delTable(tableIds);
  await getList();
  proxy?.$modal.msgSuccess('删除成功');
};

onMounted(() => {
  getList();
  getDataNameList();
});
</script>
