// src/pages/system/post/index.tsx
import { DeleteOutlined, DownloadOutlined, EditOutlined, PlusOutlined } from '@ant-design/icons';
import {
  ModalForm,
  PageContainer,
  ProFormDigit,
  ProFormRadio,
  ProFormText,
  ProFormTextArea,
  ProFormTreeSelect,
  ProTable,
  type ActionType,
  type ProColumns
} from '@ant-design/pro-components';
import { useBoolean } from 'ahooks';
import { Button, Form, message, Popconfirm, Tag } from 'antd';
import { useEffect, useMemo, useRef, useState } from 'react';
import type { DeptTreeVO } from '@/api/system/dept/types';
import type { DictData } from '@/api/system/dict/data/types';
import type { PostForm, PostQuery, PostVO } from '@/api/system/post/types';
import { addPost, delPost, getPost, listPost, postDeptTreeSelect, updatePost } from '@/api/system/post';
import EllipsisText from '@/components/common/EllipsisText';
import RowActions from '@/components/common/RowActions';
import TreePanel from '@/components/common/TreePanel';
import { useDict } from '@/hooks/useDict';
import { useTableExport } from '@/hooks/useTableExport';
import { useTableSelection } from '@/hooks/useTableSelection';
import { useUserStore } from '@/stores/userStore';
import { hasPermi } from '@/utils/permission';
import { toPageQuery, toTableData } from '@/utils/ruoyi';

const defaultPostForm: PostForm = { postSort: 0, status: '0' };

function dictOptions(dicts?: DictData[]) {
  return (dicts || []).map(item => ({ label: item.dictLabel, value: item.dictValue }));
}

interface TreeSelectNode {
  title: string;
  value: string | number;
  children?: TreeSelectNode[];
}

function toTreeSelectData(nodes: DeptTreeVO[]): TreeSelectNode[] {
  return nodes.map(node => ({
    title: node.label,
    value: node.id,
    children: node.children ? toTreeSelectData(node.children) : undefined
  }));
}

export default function SystemPostPage() {
  const actionRef = useRef<ActionType | undefined>(undefined);
  const [form] = Form.useForm<PostForm>();
  const userInfo = useUserStore(state => state.userInfo);
  const dicts = useDict('sys_normal_disable');
  const [deptOptions, setDeptOptions] = useState<DeptTreeVO[]>([]);
  const [belongDeptId, setBelongDeptId] = useState<string | number>();
  const {
    ids: selectedIds,
    selectedOne,
    handleSelectionChange,
    clearSelection
  } = useTableSelection<PostVO>(row => row.postId);
  const [modalOpen, { setTrue: openModal, setFalse: closeModal }] = useBoolean(false);
  const [modalTitle, setModalTitle] = useState('');
  const { updateExportParams, exportFile } = useTableExport();

  const canAdd = hasPermi(userInfo, ['system:post:add']);
  const canEdit = hasPermi(userInfo, ['system:post:edit']);
  const canRemove = hasPermi(userInfo, ['system:post:remove']);
  const canExport = hasPermi(userInfo, ['system:post:export']);
  useEffect(() => {
    postDeptTreeSelect().then(res => setDeptOptions(res.data || []));
  }, []);

  const treeSelectData = useMemo(() => toTreeSelectData(deptOptions), [deptOptions]);

  const openAdd = () => {
    form.resetFields();
    form.setFieldsValue(defaultPostForm);
    setModalTitle('添加岗位');
    openModal();
  };

  const openEdit = async (row?: PostVO) => {
    const target = row || selectedOne;
    if (!target?.postId) return;
    const res = await getPost(target.postId);
    form.resetFields();
    form.setFieldsValue(res.data);
    setModalTitle('修改岗位');
    openModal();
  };

  const submitForm = async (values: PostForm) => {
    values.postId ? await updatePost(values) : await addPost(values);
    message.success('操作成功');
    form.resetFields();
    actionRef.current?.reload();
    return true;
  };

  const handleDelete = async (row?: PostVO) => {
    const ids = row?.postId || selectedIds;
    await delPost(ids);
    message.success('删除成功');
    clearSelection();
    actionRef.current?.reloadAndRest?.();
  };

  const columns: ProColumns<PostVO>[] = [
    {
      title: '岗位编码',
      dataIndex: 'postCode',
      width: 140,
      render: (_, row) => <EllipsisText value={row.postCode} maxWidth={120} />
    },
    {
      title: '类别编码',
      dataIndex: 'postCategory',
      width: 130,
      render: (_, row) => <EllipsisText value={row.postCategory} maxWidth={110} />
    },
    {
      title: '岗位名称',
      dataIndex: 'postName',
      width: 140,
      render: (_, row) => <EllipsisText value={row.postName} maxWidth={120} />
    },
    {
      title: '部门',
      dataIndex: 'deptName',
      search: false,
      width: 150,
      render: (_, row) => <EllipsisText value={row.deptName} maxWidth={130} />
    },
    { title: '排序', dataIndex: 'postSort', search: false, width: 90 },
    {
      title: '状态',
      dataIndex: 'status',
      valueType: 'select',
      width: 100,
      fieldProps: { options: dictOptions(dicts.sys_normal_disable) },
      render: (_, row) => <Tag color={row.status === '0' ? 'green' : 'red'}>{row.status === '0' ? '正常' : '停用'}</Tag>
    },
    { title: '创建时间', dataIndex: 'createTime', valueType: 'dateTime', search: false, width: 170 },
    {
      title: '操作',
      valueType: 'option',
      width: 120,
      fixed: 'right',
      render: (_, row) => (
        <RowActions
          actions={[
            canEdit && { key: 'edit', label: '修改', icon: <EditOutlined />, onClick: () => openEdit(row) },
            canRemove && {
              key: 'delete',
              label: '删除',
              icon: <DeleteOutlined />,
              danger: true,
              confirm: `是否确认删除岗位编号为"${row.postId}"的数据项？`,
              onClick: () => handleDelete(row)
            }
          ]}
        />
      )
    }
  ];

  return (
    <PageContainer title="岗位管理">
      <div className="tree-table-page">
        <TreePanel
          title="部门结构"
          placeholder="请输入部门名称"
          data={deptOptions}
          fieldNames={{ title: 'label', key: 'id', children: 'children' }}
          onNodeClick={node => {
            setBelongDeptId(node.id as string | number);
            setTimeout(() => actionRef.current?.reload(), 0);
          }}
        />
        <main className="table-panel">
          <ProTable<PostVO, PostQuery>
            actionRef={actionRef}
            rowKey="postId"
            columns={columns}
            scroll={{ x: 960 }}
            search={{ labelWidth: 90 }}
            rowSelection={{ selectedRowKeys: selectedIds, onChange: handleSelectionChange }}
            request={async params => {
              const query = { ...toPageQuery(params), belongDeptId };
              updateExportParams(query);
              const res = await listPost(query);
              return toTableData(res);
            }}
            toolbar={{ title: '岗位列表' }}
            toolBarRender={() => [
              canAdd && (
                <Button key="add" type="primary" icon={<PlusOutlined />} onClick={openAdd}>
                  新增
                </Button>
              ),
              canEdit && (
                <Button key="edit" disabled={!selectedOne} icon={<EditOutlined />} onClick={() => openEdit()}>
                  修改
                </Button>
              ),
              canRemove && (
                <Popconfirm
                  key="delete"
                  title={`是否确认删除岗位编号为"${selectedIds}"的数据项？`}
                  onConfirm={() => handleDelete()}
                >
                  <Button danger disabled={!selectedIds.length} icon={<DeleteOutlined />}>
                    删除
                  </Button>
                </Popconfirm>
              ),
              canExport && (
                <Button
                  key="export"
                  icon={<DownloadOutlined />}
                  onClick={() => exportFile('/system/post/export', () => `post_${Date.now()}.xlsx`)}
                >
                  导出
                </Button>
              )
            ]}
          />
        </main>
      </div>
      <ModalForm<PostForm>
        title={modalTitle}
        open={modalOpen}
        width={560}
        form={form}
        layout="vertical"
        initialValues={defaultPostForm}
        modalProps={{ destroyOnHidden: true, onCancel: closeModal }}
        onOpenChange={open => !open && closeModal()}
        onFinish={submitForm}
      >
        <ProFormText name="postId" hidden />
        <ProFormText name="postName" label="岗位名称" rules={[{ required: true, message: '岗位名称不能为空' }]} />
        <ProFormTreeSelect
          name="deptId"
          label="部门"
          rules={[{ required: true, message: '部门不能为空' }]}
          fieldProps={{ treeDefaultExpandAll: true, treeData: treeSelectData }}
        />
        <ProFormText name="postCode" label="岗位编码" rules={[{ required: true, message: '岗位编码不能为空' }]} />
        <ProFormText name="postCategory" label="类别编码" />
        <ProFormDigit
          name="postSort"
          label="岗位顺序"
          min={0}
          rules={[{ required: true, message: '岗位顺序不能为空' }]}
        />
        <ProFormRadio.Group name="status" label="岗位状态" options={dictOptions(dicts.sys_normal_disable)} />
        <ProFormTextArea name="remark" label="备注" fieldProps={{ rows: 3 }} />
      </ModalForm>
    </PageContainer>
  );
}

// src/views/system/post/index.vue
<template>
  <div class="p-2">
    <transition :enter-active-class="proxy?.animate.searchAnimate.enter" :leave-active-class="proxy?.animate.searchAnimate.leave">
      <div v-show="showSearch" class="mb-[10px]">
        <el-card shadow="hover">
          <el-form ref="queryFormRef" :model="queryParams" :inline="true" label-width="70">
            <el-form-item label="岗位编码" prop="postCode">
              <el-input v-model="queryParams.postCode" placeholder="请输入岗位编码" clearable style="width: 240px"  style="width: 200px" @keyup.enter="handleQuery" />
            </el-form-item>
            <el-form-item label="岗位名称" prop="postName">
              <el-input v-model="queryParams.postName" placeholder="请输入岗位名称" clearable style="width: 240px"  style="width: 200px" @keyup.enter="handleQuery" />
            </el-form-item>
            <el-form-item label="状态" prop="status">
              <el-select v-model="queryParams.status" placeholder="岗位状态" clearable style="width: 240px">
                <el-option v-for="dict in sys_normal_disable" :key="dict.value" :label="dict.label" :value="dict.value" />
              </el-select>
            </el-form-item>
            <el-form-item>
              <el-button type="primary" icon="Search" @click="handleQuery">搜索</el-button>
              <el-button icon="Refresh" @click="resetQuery">重置</el-button>
            </el-form-item>
          </el-form>
        </el-card>
      </div>
    </transition>
    <el-card shadow="hover">
      <template #header>
        <el-row :gutter="10" class="mb8">
          <el-col :span="1.5">
            <el-button v-hasPermi="['system:post:add']" type="primary" plain icon="Plus" @click="handleAdd">新增</el-button>
          </el-col>
          <el-col :span="1.5">
            <el-button v-hasPermi="['system:post:edit']" type="success" plain icon="Edit" :disabled="single" @click="handleUpdate()">修改</el-button>
          </el-col>
          <el-col :span="1.5">
            <el-button v-hasPermi="['system:post:remove']" type="danger" plain icon="Delete" :disabled="multiple" @click="handleDelete()">
              删除
            </el-button>
          </el-col>
          <el-col :span="1.5">
            <el-button v-hasPermi="['system:post:export']" type="warning" plain icon="Download" @click="handleExport">导出</el-button>
          </el-col>
          <right-toolbar v-model:showSearch="showSearch" @query-table="getList"></right-toolbar>
        </el-row>
      </template>

      <el-table v-loading="loading" :data="postList" @selection-change="handleSelectionChange">
        <el-table-column type="selection" width="55" align="center" />
        <el-table-column v-if="false" label="岗位编号" align="center" prop="postId" />
        <el-table-column label="岗位编码" align="center" prop="postCode" />
        <el-table-column label="岗位名称" align="center" prop="postName" />
        <el-table-column label="岗位排序" align="center" prop="postSort" />
        <el-table-column label="状态" align="center" prop="status">
          <template #default="scope">
            <dict-tag :options="sys_normal_disable" :value="scope.row.status" />
          </template>
        </el-table-column>
        <el-table-column label="创建时间" align="center" prop="createTime" width="180">
          <template #default="scope">
            <span>{{ parseTime(scope.row.createTime) }}</span>
          </template>
        </el-table-column>
        <el-table-column label="操作" width="180" align="center" class-name="small-padding fixed-width">
          <template #default="scope">
            <el-tooltip content="修改" placement="top">
              <el-button v-hasPermi="['system:post:edit']" link type="primary" icon="Edit" @click="handleUpdate(scope.row)"></el-button>
            </el-tooltip>
            <el-tooltip content="删除" placement="top">
              <el-button v-hasPermi="['system:post:remove']" link type="primary" icon="Delete" @click="handleDelete(scope.row)"></el-button>
            </el-tooltip>
          </template>
        </el-table-column>
      </el-table>

      <pagination v-show="total > 0" v-model:page="queryParams.pageNum" v-model:limit="queryParams.pageSize" :total="total" @pagination="getList" />
    </el-card>

    <!-- 添加或修改岗位对话框 -->
    <el-dialog v-model="dialog.visible" :title="dialog.title" width="500px" append-to-body>
      <el-form ref="postFormRef" :model="form" :rules="rules" label-width="80px">
        <el-form-item label="岗位名称" prop="postName">
          <el-input v-model="form.postName" placeholder="请输入岗位名称" />
        </el-form-item>
        <el-form-item label="岗位编码" prop="postCode">
          <el-input v-model="form.postCode" placeholder="请输入编码名称" />
        </el-form-item>
        <el-form-item label="岗位顺序" prop="postSort">
          <el-input-number v-model="form.postSort" controls-position="right" :min="0" />
        </el-form-item>
        <el-form-item label="岗位状态" prop="status">
          <el-radio-group v-model="form.status">
            <el-radio v-for="dict in sys_normal_disable" :key="dict.value" :label="dict.value">{{ dict.label }}</el-radio>
          </el-radio-group>
        </el-form-item>
        <el-form-item label="备注" prop="remark">
          <el-input v-model="form.remark" type="textarea" placeholder="请输入内容" />
        </el-form-item>
      </el-form>
      <template #footer>
        <div class="dialog-footer">
          <el-button type="primary" @click="submitForm">确 定</el-button>
          <el-button @click="cancel">取 消</el-button>
        </div>
      </template>
    </el-dialog>
  </div>
</template>

<script setup name="Post" lang="ts">
import { listPost, addPost, delPost, getPost, updatePost } from '@/api/system/post';
import { PostForm, PostQuery, PostVO } from '@/api/system/post/types';

const { proxy } = getCurrentInstance() as ComponentInternalInstance;
const { sys_normal_disable } = toRefs<any>(proxy?.useDict('sys_normal_disable'));

const postList = ref<PostVO[]>([]);
const loading = ref(true);
const showSearch = ref(true);
const ids = ref<Array<number | string>>([]);
const single = ref(true);
const multiple = ref(true);
const total = ref(0);

const postFormRef = ref<ElFormInstance>();
const queryFormRef = ref<ElFormInstance>();

const dialog = reactive<DialogOption>({
  visible: false,
  title: ''
});

const initFormData: PostForm = {
  postId: undefined,
  postCode: '',
  postName: '',
  postSort: 0,
  status: '0',
  remark: ''
};

const data = reactive<PageData<PostForm, PostQuery>>({
  form: { ...initFormData },
  queryParams: {
    pageNum: 1,
    pageSize: 10,
    postCode: '',
    postName: '',
    status: ''
  },
  rules: {
    postName: [{ required: true, message: '岗位名称不能为空', trigger: 'blur' }],
    postCode: [{ required: true, message: '岗位编码不能为空', trigger: 'blur' }],
    postSort: [{ required: true, message: '岗位顺序不能为空', trigger: 'blur' }]
  }
});

const { queryParams, form, rules } = toRefs<PageData<PostForm, PostQuery>>(data);

/** 查询岗位列表 */
const getList = async () => {
  loading.value = true;
  const res = await listPost(queryParams.value);
  postList.value = res.rows;
  total.value = res.total;
  loading.value = false;
};
/** 取消按钮 */
const cancel = () => {
  reset();
  dialog.visible = false;
};
/** 表单重置 */
const reset = () => {
  form.value = { ...initFormData };
  postFormRef.value?.resetFields();
};
/** 搜索按钮操作 */
const handleQuery = () => {
  queryParams.value.pageNum = 1;
  getList();
};
/** 重置按钮操作 */
const resetQuery = () => {
  queryFormRef.value?.resetFields();
  handleQuery();
};
/** 多选框选中数据 */
const handleSelectionChange = (selection: PostVO[]) => {
  ids.value = selection.map((item) => item.postId);
  single.value = selection.length != 1;
  multiple.value = !selection.length;
};
/** 新增按钮操作 */
const handleAdd = () => {
  reset();
  dialog.visible = true;
  dialog.title = '添加岗位';
};
/** 修改按钮操作 */
const handleUpdate = async (row?: PostVO) => {
  reset();
  const postId = row?.postId || ids.value[0];
  const res = await getPost(postId);
  Object.assign(form.value, res.data);
  dialog.visible = true;
  dialog.title = '修改岗位';
};
/** 提交按钮 */
const submitForm = () => {
  postFormRef.value?.validate(async (valid: boolean) => {
    if (valid) {
      form.value.postId ? await updatePost(form.value) : await addPost(form.value);
      proxy?.$modal.msgSuccess('操作成功');
      dialog.visible = false;
      await getList();
    }
  });
};
/** 删除按钮操作 */
const handleDelete = async (row?: PostVO) => {
  const postIds = row?.postId || ids.value;
  await proxy?.$modal.confirm('是否确认删除岗位编号为"' + postIds + '"的数据项？');
  await delPost(postIds);
  await getList();
  proxy?.$modal.msgSuccess('删除成功');
};
/** 导出按钮操作 */
const handleExport = () => {
  proxy?.download(
    'system/post/export',
    {
      ...queryParams.value
    },
    `post_${new Date().getTime()}.xlsx`
  );
};

onMounted(() => {
  getList();
});
</script>
